project:
  type: book
  output-dir: docs

lang: nb

book:
  title: "MAT221 Diskret matematikk"
  author: "Morten Brun"
  reader-mode: true
  chapters:
    - index.qmd
    - notes/uke34.qmd

number-depth: 2

crossref:
  thm-title: "Teorem"
  thm-prefix: "Teorem"
  cor-title: "Korollar"
  cor-prefix: "Korollar"
  exr-title: "Oppgave"
  exr-prefix: "Oppgave"
  exm-title: "Eksempel"
  exm-prefix: "Eksempel"

format:
  html:
    html-math-method: mathml
    theme:
      light: cosmo
      dark: darkly
    respect-user-color-scheme: true
    toc: true
    number-sections: true
    code-copy: true

  pdf:
    documentclass: scrreprt
    number-sections: true
    include-in-header:
      text: |
        \setcounter{MaxMatrixCols}{30}

execute:
  freeze: auto
